- src/guide/contributing/translations.md
Correção de algumas palavras e erro de digitação.
> Traduzir "guide/contributing/translations.md"

- src/guide/template-syntax.md
This pull request includes the translation of the `guide/template-syntax.md` file to Brazilian Portuguese.
> translate guide/template-syntax.md to pt-br

- src/guide/component-basics.md
Translation of guides/component-basics.md file
Closes: #11
> translate guides/component-basics

- src/guide/list.md
> Translate "guide/list"

- src/guide/component-edge-cases.md
File translation completed 'component-edge-cases'.
> docs: Translate file 'guide/component-edge-cases'

- src/guide/forms.md
Translation of the guide/forms with correct links of the pens translated from the original
closes #10
> translated guide/forms

- src/guide/forms.md
Este PR visa atualizar alguns pontos da tradução realizada em guide/forms.
@ErickPetru Poderia, por gentileza, colocar os pens desta collection no perfil do vuejs-br? https://codepen.io/collection/AyeLea
> docs: update guide/forms translation

- src/guide/component-edge-cases.md
> Fix merge problems on "component-edge-cases.md"

- src/guide/conditional.md
> Fix merge problems on "conditional.md"

- src/guide/routing.md
Tradução da página `/src/guide/routing.md`
closes #128
> página routing.md traduzida para ptbr

- src/coc/index.md
> docs: Translate file 'coc/index'

- src/guide/component-basics.md
> Corrects gender misspelling

- src/guide/migration/v-bind.md
> docs: translate guide/migration/v-bind

- src/guide/contributing/translations.md
> Melhorando lista de termos traduzidos

- src/guide/class-and-style.md
docs: portuguese translation 
closes #6 "guide/class-and-style.md"
> Translates "guide/class-and-style.md" #6

- src/guide/events.md
Waiting for review.
docs: translate "guide/events.md" closes #9 
Os exemplos do CodePen que foram traduzidos estão em uma coleção na minha conta e podem ser acessados através dos seguintes links:
- https://codepen.io/edumedeiros/pen/OJNqgmj
- https://codepen.io/edumedeiros/pen/gOrERRW
- https://codepen.io/edumedeiros/pen/abNMwLo
> docs: translate "guide/events.md" #9

- src/guide/component-dynamic-async.md
File translation completed 'component-dynamic-async'.
closes #17
> docs: Translate file component-dynamic-async

- src/guide/component-props.md
This pull request includes the translation of the guide/component-props.md file to Brazilian Portuguese.
closes #12
> Translates "guide/component-props.md"

- src/guide/optimizations.md
> translated optimizations to pt-BR

- src/guide/mobile.md
> Translating mobile.md page to pt-Br

- src/guide/ssr.md
> Translation of the 'ssr' file of the docs

- src/guide/state-management.md
> guide: Translates state-management to pt-br

- src/support-vuejs/README.md
closes #57 
Estou abrindo esse merge em adianto.
Caso não seja recomendado pode fechar.
> Translate support readme

- src/community/join.md
> docs: Translate File 'community/join.md'

- src/.vuepress/components/common/vuemastery-video-modal.vue
- src/.vuepress/theme/components/Newsletter.vue
- src/.vuepress/theme/components/sponsors/OpenCollectiveSponsors.vue
- src/.vuepress/theme/components/sponsors/PatreonSponsors.vue
- src/.vuepress/theme/components/sponsors/SpecialSponsors.vue
- src/.vuepress/theme/data/patreon-sponsors.js
- src/README.md
> Tradução da página Home

- src/guide/migration/v-if-v-for.md
> translated v-if-v-for.md to pt-BR

- src/guide/migration/array-refs.md
> translated guide/migration/array-refs.md to pt-BR

- src/guide/migration/fragments.md
> docs: translate guide/migration/fragments

- src/guide/migration/transition.md
> docs: translate guide/migration/transition

- src/community/partners.md
> docs: Translate file 'community/partners'

- src/community/team.md
> docs: Translate file 'community/team'

- src/community/themes.md
> Translate file 'community/themes'

- src/guide/composition-api-lifecycle-hooks.md
> Translate "guide/composition-api-lifecycle-hooks.md"

- src/guide/instance.md
> docs: Translate file 'guide/instance.md'

- src/guide/migration/key-attribute.md
> Docs: Translation of guide/migration/key-attribute.md to Portuguese

- src/guide/mixins.md
> translation of the mixins.md file was carried out to resolve issue 120

- src/guide/migration/v-model.md
> docs: translate guide/migration/v-model.md

- src/guide/migration/props-default-this.md
> docs: translate "guide/migration/props-default-this.md"

- src/.vuepress/config.js
> Translation of the menu

- src/guide/render-function.md
> Translation render function

- src/guide/composition-api-setup.md
- src/guide/transitions-overview.md
This PR translates the transitions-overview section to Portuguese. 
closes #136
closes #117
> Docs: translate guide/transitions-overview.md

- src/guide/migration/filters.md
> docs: translate "guide/migration/filters.md"

- src/guide/migration/events-api.md
> docs: translate "guide/migration/events-api.md"

- src/guide/migration/render-function-api.md
> Traduzir "guide/migration/render-function-api.md"

- src/guide/migration/introduction.md
> Translates src/guide/migration/introduction

- src/guide/migration/slots-unification.md
> Translates src/guide/migration/slots-unification

- src/guide/migration/global-api-treeshaking.md
> docs: translate guide/migration/global-api-treeshaking

- src/guide/migration/data-option.md
Traduzi novamente a mesma página, somente colocada em outra branch, evitando problemas anteriores.
closes #89
> Docs: Translation of guide/migration/data-option.md

- src/guide/migration/functional-components.md
Novo pull request para resolver problemas anteriores
closes #93
> Docs: Translation of guide/migration/functional-components.md

- src/guide/component-registration.md
> Translate "guide/component-registration.md"

- src/guide/a11y-standards.md
> Docs: Translate a11y-standards to Portuguese (BR)

- src/guide/migration/async-components.md
Novo pull request feito em branch separada, evitando conflitos causados na tentativa anterior
closes #85
> Docs: Translation of guide/migration/async-components.md

- src/guide/a11y-resources.md
> Docs: translate a11y-resources to Portuguese (BR)

- src/guide/composition-api-provide-inject.md
> Translate "guide/composition-api-provide-inject.md"

- src/guide/a11y-semantics.md
> docs: translate guides/a11y-semantics

- src/guide/composition-api-introduction.md
> Translate "guide/composition-api-introduction.md"

- src/guide/single-file-component.md
> Translation of the 'single-file-component' file of the docs

- src/guide/plugins.md
> Translation of the 'plugins' file of the docs

- src/api/refs-api.md
Traduzir api/refs-api.md
closes #82
> Traduzir api/refs-api

- src/api/options-data.md
Complete Translation of Options-Data to portuguese.
closes #78
> Docs: translate src/api/options-data.md

- src/api/options-api.md
- src/api/options-assets.md
> Translate "api/options-assets.md"

- src/cookbook/editable-svg-icons.md
Complete Translation of editable-svg-icons to portuguese.
closes #59
> Docs: translate cookbook/editable-svg-icons.md

- src/api/built-in-components.md
Complete Translation of built-in-components to portuguese
closes #69
> Translation of api/built-in-components.md to portuguese

- src/guide/change-detection.md
Made translation of this file for the documentation
closes #112
> Translate guide/change-detection

- src/api/directives.md
Complete Translation of Api/Directives to portuguese.
closes #72
> Docs: translate src/api/directives.md

- src/api/basic-reactivity.md
> Tradução de "api/basic-reactivity.md"

- src/api/special-attributes.md
> Tradução de  "api/special-attributes.md"

- src/guide/migration/attribute-coercion.md
> Tradução de "guide/migration/attribute-coercion.md"

- src/guide/migration/custom-directives.md
> Tradução de "guide/migration/custom-directives.md"

- src/api/composition-api.md
- src/guide/component-template-refs.md
> Translating "api/composition-api.md"

- src/api/options-misc.md
> Translation of options-misc.md to pt-BR

- src/guide/class-and-style.md
- src/guide/computed.md
- src/guide/conditional.md
- src/guide/data-methods.md
- src/guide/events.md
- src/guide/forms.md
- src/guide/installation.md
- src/guide/list.md
> Translating new VueSchool links

- src/api/options-data.md
Updated the translation of "2. api/options-data - 1 e 2".
closes #255
> Update translation: api/options-data

- src/guide/testing.md
Testing article translated
closes #133
> docs: translating guide/testing.md

- src/cookbook/index.md
closes #60
https://github.com/vuejs-br/docs-next/issues/60
> Translate cookbook index.md file to Portuguese

- src/api/application-config.md
> Translate application-config md file to Portuguese

- src/guide/migration/v-if-v-for.md
> Translate new v-if-v-for md file segment to Portuguese

- src/guide/migration/async-components.md
> Async components upstream change

- src/guide/contributing/translations.md
Revisei o arquivo como indicado mas não vi a necessidade de alterar nada alem da tradução
closes #266
> docs: fixing topics in guide contributing translations

- src/api/global-api.md
> Translation of api/global-api

- src/.vuepress/components/community/team/get-position-button.vue
- src/.vuepress/components/community/team/index.vue
- src/.vuepress/components/community/team/vuer-profile.vue
- src/api/built-in-components.md
- src/api/composition-api.md
- src/api/directives.md
- src/api/options-composition.md
- src/api/options-data.md
- src/guide/composition-api-setup.md
- src/guide/migration/migration-build.md
> Translate final upstream merge additions
